### ISSUE TITLE
Copyright notice not properly applied

### ISSUE THREAD

**Issue by mattmook** [theheraldproject/herald-for-ios#161]
Looking through the source code, I note that the project contains a substantial proportion of code written in the https://github.com/daisuke-t-jp/xxHash-Swift project by @daisuke-t-jp. Indeed as far as I can tell other than bundling all the source code in one file there are no real "adaptations" to the source files - applying the Herald Project Contributors copyright notice to the file feels incredibly misleading.

Given that the xxHash-Swift project is published under an MIT licence, it's licence should be included alongside this project, yet looking at the LICENCE.txt and NOTICE.txt files of herald-for-ios there is no mention of xxHash-Swifts licence.

For the record the projects licence can be found at https://github.com/daisuke-t-jp/xxHash-Swift/blob/master/LICENSE

**Expected behavior**

NOTICE file or LICENCE file should be updated to clearly denote software that has been copied from elsewhere.

Herald Project Contributors copyright notice should be removed from the file https://github.com/theheraldproject/herald-for-ios/blob/develop/Herald/Herald/Sensor/Payload/Simple/XXH3.swift

**Comment by adamfowleruk** [comment]
Investigating this now, thanks.

**Comment by adamfowleruk** [comment]
Thanks. This functionality has been replaced in an upcoming PR for v2.1.
